#!/usr/bin/env python3
from __future__ import annotations

import base64
import json
import os
import shutil
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dtvs.common.canonical_json import dumps
from dtvs.common.hashing import sha256_file
from dtvs.contracts.signing import generate_private_key, public_key_bytes

VERSION = "0.1.0"
NAME = "DTVS-Worker-Pack-v0.1.0-Windows-x64"


def copy_tree(src: Path, dst: Path) -> None:
    ignore = shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache", "runs", "inputs", "reports", "dist")
    shutil.copytree(src, dst, ignore=ignore)


def main() -> int:
    dist = ROOT / "dist"
    staging = dist / NAME
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True, exist_ok=True)
    copy_tree(ROOT / "dtvs", staging / "dtvs")
    for rel in [
        "dtvs_worker_cli.py",
        "dtvs-worker.ps1",
        "START_DTVS_WORKER.cmd",
        "schemas/task_bundle_v022.schema.json",
        "docs/FAILURE_CODES.md",
        "docs/WORKER_PACK_V0.1_WINDOWS_INSTALL_CN.md",
    ]:
        src = ROOT / rel
        dst = staging / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
    (staging / "README_WORKER_PACK.txt").write_text(
        "\n".join(
            [
                "DTVS Worker Pack v0.1.0",
                "",
                "Public commands:",
                "  .\\dtvs-worker.ps1 doctor",
                "  .\\dtvs-worker.ps1 run --package <task-package.zip> --workspace D:\\DTVS",
                "  .\\dtvs-worker.ps1 export --workspace D:\\DTVS --run-id <run_id> --destination <drive>",
                "  .\\dtvs-worker.ps1 submit --workspace D:\\DTVS --run-id <run_id> --assignment <assignment.json>",
                "",
                "FFmpeg, restoration models, NVIDIA drivers, Python, and licensed media are not bundled.",
                "No RTX 4060 render result is included in this package.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    zip_path = dist / f"{NAME}.zip"
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in sorted(staging.rglob("*")):
            if path.is_file():
                zf.write(path, path.relative_to(dist).as_posix())
    digest = sha256_file(zip_path)
    (dist / f"{NAME}.zip.sha256").write_text(f"{digest}  {NAME}.zip\n", encoding="utf-8")
    key = generate_private_key()
    manifest = {
        "schema_version": "0.2.2",
        "release_name": NAME,
        "worker_pack_version": VERSION,
        "built_at": datetime.now(timezone.utc).isoformat(),
        "target": "Windows x64",
        "zip": {"path": f"dist/{NAME}.zip", "sha256": digest, "bytes": zip_path.stat().st_size},
        "entrypoints": ["dtvs-worker.ps1", "START_DTVS_WORKER.cmd"],
        "public_commands": [
            ".\\dtvs-worker.ps1 doctor",
            ".\\dtvs-worker.ps1 run --package <任务包路径> --workspace D:\\DTVS",
            ".\\dtvs-worker.ps1 export --workspace D:\\DTVS --run-id <run_id> --destination <移动硬盘路径>",
            ".\\dtvs-worker.ps1 submit --workspace D:\\DTVS --run-id <run_id> --assignment <assignment.json>",
        ],
        "not_bundled_due_to_license_or_operator_control": [
            "FFmpeg binaries",
            "Real-ESRGAN executable and model files",
            "NVIDIA drivers",
            "Task inputs",
            "Rendered outputs",
            "Cloudflare secrets",
        ],
        "integrity": {
            "state_limit": "Worker highest public return state is READY_FOR_RETURN; ACCEPTED is not generated by Worker Pack",
            "power_gate": "Power sampling is diagnostic only in v0.1.0",
            "mock_notice": "No mock result is an RTX 4060 real render measurement",
        },
        "release_manifest_public_key_b64": base64.b64encode(public_key_bytes(key)).decode("ascii"),
    }
    signature = key.sign(dumps(manifest))
    (dist / "worker_release_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    (dist / "worker_release_manifest.sig").write_text(base64.b64encode(signature).decode("ascii") + "\n", encoding="ascii")
    shutil.rmtree(staging)
    print(json.dumps({"zip": str(zip_path), "sha256": digest, "manifest": str(dist / "worker_release_manifest.json")}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

